# Generated by Django 4.2.11 on 2025-03-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing.uploadedfile')),
            ],
        ),
    ]
