# Generated by Django 4.2.11 on 2025-03-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_image', models.ImageField(upload_to='diagrams/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing.codefile')),
            ],
        ),
    ]
